#1. Display all customers who live in 'Delhi'.
select name,city from customers where city = "Delhi";

#2. Find the average rating of all restaurants in 'Mumbai'.
select avg(rating) as avg_rating from restaurants 
where city = "Mumbai"; 

#3. List all customers who have placed at least one order.
select distinct(c.name), o.order_id from customers c join orders o using(customer_id);

#4. Display the total number of orders placed by each customer.
with temp as (select customer_id, count(order_id) as total_count_of_orders 
from orders group by customer_id) select c.name, t.total_count_of_orders 
from customers c join temp t using(customer_id);

#5. Find the total revenue generated by each restaurant.
with temp as (select restaurant_id, sum(total_amount) as total_rev_per_restaurant 
from orders group by restaurant_id) select r.name, t.total_rev_per_restaurant 
from restaurants r inner join temp t using(restaurant_id);

#6. Find the top 5 restaurants with the highest average rating.
with temp as (select restaurant_id, avg(rating) as avg_ratings from restaurants group by restaurant_id)
select r.name, t.avg_ratings from restaurants r join temp t using(restaurant_id) ORDER BY t.avg_ratings DESC
LIMIT 5;

#7. Display all customers who have never placed an order.
select c.name, o.order_id from customers c left join orders o using(customer_id) where o.order_id is null;

#8. Find the number of orders placed by each customer in 'Mumbai'.
with temp as (select customer_id, count(order_id) as order_counts from orders group by customer_id) 
select c.name, t.order_counts from customers c join temp t using(customer_id) where city="Mumbai";

#9. Display all orders placed in the last 30 days
select c.customer_id, c.name, o.order_id, o.order_date 
from customers c inner join orders o using(customer_id) where o.order_date >= current_date - interval 30 day;

#10. List all delivery partners who have completed more than 1 delivery
select partner_id, count(*) from orderdelivery group by partner_id having count(*)>1;

#11. Find the customers who have placed orders on exactly three different days.
select c.customer_id, c.name, count(distinct date(o.order_date)) as unique_order_date 
from customers c join orders o using(customer_id) group by c.customer_id, c.name 
having unique_order_date = 3;

#12. Find the delivery partner who has worked with the most different customers.
select dp.partner_id, dp.name, count(distinct o.customer_id) as distinct_customer_count
from orders o join orderdelivery od using(order_id) join deliverypartners dp using(partner_id) 
group by dp.partner_id, dp.name order by distinct_customer_count desc limit 1;

#13. Identify customers who have the same city and have placed orders at the same restaurants, but on different dates.
select c1.customer_id as customer1_id, c1.name as customer1_name,
       c2.customer_id as customer2_id, c2.name as customer2_name,
       r.name as restaurant_name, r.city,
       o1.order_date as customer1_order_date,
       o2.order_date as customer2_order_date
from customers c1
join orders o1 on c1.customer_id = o1.customer_id
join restaurants r on o1.restaurant_id = r.restaurant_id
join customers c2 on c1.city = c2.city and c1.customer_id < c2.customer_id
join orders o2 on c2.customer_id = o2.customer_id and o1.restaurant_id = o2.restaurant_id
where o1.order_date <> o2.order_date;
